services:
  - type: web
    name: ezan-il-ilce-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
   startCommand: bash start.sh
    branch: main
    autoDeploy: true

  - type: cron
    name: daily-updater
    env: python
    schedule: "0 3 * * *"  # Her gün saat 03:00'te UTC
    command: python cron-updater.py
