services:
  - type: web
    name: ezan-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    branch: main
    autoDeploy: true

  - type: cron
    name: daily-updater
    env: python
    schedule: "0 3 * * *"  # Her gün saat 03:00'te UTC
    command: python cron-updater.py
